package org.meta.conf;

/**
 * Enumeration of all configuation options
 * @author mark
 */
public enum ConfId {
	CONF_TWITTER_USERID,
	CONF_TWITTER_PASSWORD,
	CONF_TWITTER_USERAGENT,
	CONF_TWITTER_SOURCE,
	CONF_TWITTER_CONSUMER,
	CONF_TWITTER_CONSUMER_SECRET,
	CONF_TWITTER_TOKEN_FILE,

	CONF_MUSIC_FOLDER,
	CONF_MUSIC_STATS,
	CONF_MUSIC_ISSUES,
	CONF_MUSIC_FIX,
	CONF_MUSIC_PRINTSTATS,
	CONF_MUSIC_PRINTISSUES,
}